language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

branches:
  only:
    - master

matrix:
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 7.0
    - php: nightly

before_script: composer update --prefer-source ${PREFER_LOWEST}

script: phpunit --coverage-text
